"""Tasks: drop unique constraint for user_id column

Revision ID: 9f92a1395868
Revises: fb743fe53b5a
Create Date: 2025-01-28 19:33:46.166483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f92a1395868'
down_revision: Union[str, None] = 'fb743fe53b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_user_id_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_user_id_key', 'tasks', ['user_id'])
    # ### end Alembic commands ###
