"""Tasks model: Add user_id column

Revision ID: fb743fe53b5a
Revises: 043d2bf725a0
Create Date: 2025-01-28 18:19:18.644729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb743fe53b5a'
down_revision: Union[str, None] = '043d2bf725a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'tasks', ['user_id'])
    op.create_foreign_key(None, 'tasks', 'user_profile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
