"""Correct UserProfile: remove access_token attribute

Revision ID: 043d2bf725a0
Revises: cf9f7557516d
Create Date: 2025-01-27 17:54:05.412541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043d2bf725a0'
down_revision: Union[str, None] = 'cf9f7557516d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('user_profile', 'password')
    op.drop_column('user_profile', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_profile', 'hashed_password')
    # ### end Alembic commands ###
